# Generated by Django 4.0.3 on 2022-04-28 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_account_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='charactor',
            field=models.SmallIntegerField(choices=[(1, '小吃铺'), (2, '消费者')], default=2, verbose_name='身份'),
        ),
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.EmailField(default='xxx@qq.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='account',
            name='description',
            field=models.CharField(default='description test', max_length=35),
        ),
    ]
