# Generated by Django 4.0.3 on 2022-04-28 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_account_charactor_account_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='charactor',
            field=models.CharField(choices=[(1, '小吃铺'), (2, '消费者')], default='消费者', max_length=5, verbose_name='身份'),
        ),
    ]
