# Generated by Django 4.0.3 on 2022-06-02 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_account_charactor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=30)),
                ('score', models.IntegerField(default=5)),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='charactor',
            field=models.CharField(choices=[(1, '小吃铺'), (2, '消费者')], default='消费者', max_length=5, verbose_name='identity'),
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('location', models.CharField(choices=[(1, '小区1'), (2, '小区2'), (3, '小区3')], max_length=10, verbose_name='location')),
                ('belong_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account', verbose_name='摊主')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=50)),
                ('state', models.CharField(choices=[(1, '已下单'), (2, '摊主已接单'), (3, '订单已完成')], max_length=10)),
                ('create_time', models.TimeField(auto_now_add=True)),
                ('res', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.restaurant')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account')),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='belong_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.restaurant'),
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=50)),
                ('create_time', models.TimeField(auto_now=True)),
                ('res', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.restaurant')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account')),
            ],
        ),
    ]
