# Generated by Django 4.0.3 on 2022-06-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_food_alter_account_charactor_restaurant_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='nickname',
            field=models.CharField(default='给自己一个名称吧', max_length=10),
        ),
    ]
