# Generated by Django 4.0.3 on 2022-06-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_account_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='charactor',
            field=models.SmallIntegerField(choices=[(1, '小吃铺'), (2, '消费者')], default='消费者', max_length=5, verbose_name='identity'),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.SmallIntegerField(choices=[(1, '已下单'), (2, '摊主已接单'), (3, '订单已完成')], max_length=10),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='location',
            field=models.SmallIntegerField(choices=[(1, '小区1'), (2, '小区2'), (3, '小区3')], max_length=10, verbose_name='location'),
        ),
    ]
