# Generated by Django 4.0.3 on 2022-06-02 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_order_target_food_price_order_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='belong_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account'),
        ),
    ]
