# Generated by Django 4.0.3 on 2022-06-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_restaurant_belong_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='average_score',
            field=models.FloatField(default=4),
        ),
    ]
