# Generated by Django 4.0.3 on 2022-06-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_food_ordernum'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='year',
            field=models.IntegerField(default=2022),
        ),
    ]
