# Generated by Django 4.0.3 on 2022-06-10 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_order_create_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='year',
        ),
        migrations.AlterField(
            model_name='order',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 10, 8, 22, 11, 374372)),
        ),
    ]
