# Generated by Django 4.0.3 on 2022-06-10 08:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_order_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 10, 8, 48, 15, 900888, tzinfo=utc)),
        ),
    ]
