# Generated by Django 4.0.3 on 2022-06-28 12:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_account_checkcode_account_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='resname',
            field=models.CharField(default='店铺1', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='username',
            field=models.CharField(default='zike', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 28, 12, 14, 49, 386620, tzinfo=utc)),
        ),
    ]
